name: Test

on:
  push:
    branches:
    - develop
  pull_request:

jobs:
  cpp:
    name: 'C++ tests'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install bison flex libomp
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
    - uses: actions/cache@v2
      if: matrix.os == 'windows-latest'
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-chocolatey-cpp-0
        restore-keys: |
          ${{ runner.os }}-chocolatey-cpp-
          ${{ runner.os }}-chocolatey-
    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      run: choco install winflexbison3 --version 2.5.18.20190508
    - name: Configure
      run: cmake . -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: cmake --build . --parallel 5
    - name: Test
      run: ctest -C Debug --output-on-failure

  python:
    name: Python tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        python:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel pytest
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y swig
    - name: Install dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install bison flex swig libomp
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
    - uses: actions/cache@v2
      if: matrix.os == 'windows-latest'
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-chocolatey-python-1
        restore-keys: |
          ${{ runner.os }}-chocolatey-python-
          ${{ runner.os }}-chocolatey-
    - name: Install dependencies
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        choco install winflexbison3 --version 2.5.18.20190508
        choco install swig --version 4.0.1
    - name: Select build type
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: echo "OPENQL_BUILD_TYPE=Release" >> $GITHUB_ENV
    - name: Select build type
      if: matrix.os != 'windows-latest'
      run: echo "OPENQL_BUILD_TYPE=Debug" >> $GITHUB_ENV
    - name: Build
      working-directory: qxelarator
      run: python -m pip install --verbose .
    - name: Test
      working-directory: qxelarator
      run: python -m pytest
